config/routes.rb
BillForm::Application.routes.draw do
  resources :credit_cards

  get "home/index"

   root :to => 'home#index'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
	validates :cardholder, :presence => true
	validates :number, :presence => true, :number => true
	validates :expiration, :presence => true, :expiration => true
	validates :email, :presence => true, :email => true
	validates :code, :presence => true
	validates :company, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

 # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credit_cards }
    end
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
    @credit_card = CreditCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credit_card }
    end
  end

  # GET /credit_cards/new
  # GET /credit_cards/new.json
  def new
    @credit_card = CreditCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit_card }
    end
  end

  # GET /credit_cards/1/edit
  def edit
    @credit_card = CreditCard.find(params[:id])
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(params[:credit_card])

    respond_to do |format|
      if @credit_card.save
	CreditCardMailer.new_user_email(@credit_card).deliver
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render json: @credit_card, status: :created, location: @credit_card }
      else
        format.html { render action: "new" }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credit_cards/1
  # PUT /credit_cards/1.json
  def update
    @credit_card = CreditCard.find(params[:id])

    respond_to do |format|
      if @credit_card.update_attributes(params[:credit_card])
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card = CreditCard.find(params[:id])
    @credit_card.destroy

    respond_to do |format|
      format.html { redirect_to credit_cards_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_card_validator.rb
#From https://gist.github.com/1182499

class CreditCardValidator <ActiveModel::EachValidator
	def validate(record, attribute, number)
	  number = number.to_s.gsub(/\D/, "")

	  error(attribute) unless valid_association?(number)
	  number.reverse!

	  relative_number = {'0' => 0, '1' => 2, '2' => 4, '3' => 6, '4' => 8, '5' => 1, '6' => 3, '7' => 5, '8' => 7, '9' => 9}

	  sum = 0

	  number.split("").each_with_index do |n, i|
	    sum += (i.even?) ? n.to_i : relative_number[n]
	  end

	  sum % 10 == 0
	end

	def valid_association?(number)
	  number = number.to_s.gsub(/\D/, "")

	  return :dinners if number.length == 14 && number =~ /^3(0[0-5]|[68])/ # 300xxx-305xxx, 36xxxx, 38xxxx
	  return :amex if number.length == 15 && number =~ /^3[47]/ # 34xxxx, 37xxxx
	  return :visa if [13,16].include?(number.length) && number =~ /^4/ # 4xxxxx
	  return :master if number.length == 16 && number =~ /^5[1-5]/ # 51xxxx-55xxxx
	  return :discover if number.length == 16 && number =~ /^6011/ # 6011xx
	  return nil
	end
	
	def error(attribute)
		record.errors[attribute] << (options[:message] || "invalid credit card number")
	end
end

app/helpers/credit_cards_helper.rb
#From https://gist.github.com/1182499

module CreditCardsHelper
	def valid_credit_card?(number)
	  number = number.to_s.gsub(/\D/, "")

	  return false unless valid_association?(number)
	  number.reverse!

	  relative_number = {'0' => 0, '1' => 2, '2' => 4, '3' => 6, '4' => 8, '5' => 1, '6' => 3, '7' => 5, '8' => 7, '9' => 9}

	  sum = 0

	  number.split("").each_with_index do |n, i|
	    sum += (i.even?) ? n.to_i : relative_number[n]
	  end

	  sum % 10 == 0
	end

	def valid_association?(number)
	  number = number.to_s.gsub(/\D/, "")

	  return :dinners if number.length == 14 && number =~ /^3(0[0-5]|[68])/ # 300xxx-305xxx, 36xxxx, 38xxxx
	  return :amex if number.length == 15 && number =~ /^3[47]/ # 34xxxx, 37xxxx
	  return :visa if [13,16].include?(number.length) && number =~ /^4/ # 4xxxxx
	  return :master if number.length == 16 && number =~ /^5[1-5]/ # 51xxxx-55xxxx
	  return :discover if number.length == 16 && number =~ /^6011/ # 6011xx
	  return nil
	end
end

app/helpers/email_validator.rb
class EmailValidator <ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		throw_error(record,attribute) unless value =~ /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}/
	end
	
	def throw_error(record, attribute)
		record.errors[attribute] << (options[:message] || "invalid email address")
	end
end

app/helpers/expiration_validator.rb
#From https://gist.github.com/1182499

class ExpirationValidator <ActiveModel::EachValidator
	def validate_each(record, attribute, value)
		throw_error(record,attribute) unless value =~ /^((1[0-2])|(0{0,1}[1-9]{1}))(\/(((0{0,1}[1-9])|([12][1-9]))|(3[01])){0,1}){0,1}?\/20[0-9]{2}$/
	end
	
	def throw_error(record, attribute)
		record.errors[attribute] << (options[:message] || "date is invalid")
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/number_validator.rb
#From https://gist.github.com/1182499

class NumberValidator <ActiveModel::EachValidator
	def validate_each(record, attribute, number)
	  number = number.to_s.gsub(/\D/, "")
	  
	  throw_error(record,attribute) unless valid_association?(number)
	  number.reverse!

	  relative_number = {'0' => 0, '1' => 2, '2' => 4, '3' => 6, '4' => 8, '5' => 1, '6' => 3, '7' => 5, '8' => 7, '9' => 9}

	  sum = 0

	  number.split("").each_with_index do |n, i|
	    sum += (i.even?) ? n.to_i : relative_number[n]
	  end

	  throw_error(record,attribute) unless sum % 10 == 0
	end

	def valid_association?(number)
	  number = number.to_s.gsub(/\D/, "")

	  return :dinners if number.length == 14 && number =~ /^3(0[0-5]|[68])/ # 300xxx-305xxx, 36xxxx, 38xxxx
	  return :amex if number.length == 15 && number =~ /^3[47]/ # 34xxxx, 37xxxx
	  return :visa if [13,16].include?(number.length) && number =~ /^4/ # 4xxxxx
	  return :master if number.length == 16 && number =~ /^5[1-5]/ # 51xxxx-55xxxx
	  return :discover if number.length == 16 && number =~ /^6011/ # 6011xx
	  return nil
	end
	
	def throw_error(record, attribute)
		record.errors[attribute] << (options[:message] || "invalid credit card number")
	end
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cardholder %><br />
    <%= f.text_field :cardholder %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label "Expiration Date (MM/DD/YYYY or MM/YYYY)" %><br />
    <%= f.text_field :expiration %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing credit_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<h1>Listing credit cards</h1>

<table>
  <tr>
    <th>Cardholder</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @credit_cards.each do |credit_card| %>
  <tr>
    <td><%= credit_card.cardholder %></td>
    <td><%= link_to 'Show', credit_card %></td>
    <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
    <td><%= link_to 'Destroy', credit_card, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Credit card', new_credit_card_path %>
<%= link_to 'Back to Home', root_path %>

app/views/credit_cards/new.html.erb
<h1>New credit_card</h1>

<%= render 'form' %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cardholder:</b>
  <%= @credit_card.cardholder %>
</p>

<p>
  <b>Number:</b>
  <%= @credit_card.number %>
</p>

<p>
  <b>Expiration:</b>
  <%= @credit_card.expiration %>
</p>

<p>
  <b>Code:</b>
  <%= @credit_card.code %>
</p>

<p>
  <b>Company:</b>
  <%= @credit_card.company %>
</p>

<p>
  <b>Email:</b>
  <%= @credit_card.email %>
</p>


<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>

app/views/home/index.html.erb
<h1>home#index</h1>
<%= link_to "Enter new credit card info", new_credit_card_path %><br>
<%= link_to "View all credit card info", credit_cards_path %><br><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BillForm</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>